'use client'
import { useState } from 'react'

export default function BlogGen() {
  const [topic, setTopic] = useState('free online tools')
  const [tone, setTone] = useState('informative')

  const generate = () => {
    const intros = {
      informative: `In this comprehensive guide, we'll explore ${topic} and why they matter in 2026.`,
      casual: `Let's talk about ${topic} – honestly, they're game-changers.`,
      professional: `This article examines the strategic importance of ${topic} for modern businesses.`
    }

    return `# ${topic.charAt(0).toUpperCase() + topic.slice(1)}: The Complete 2026 Guide

${intros[tone as keyof typeof intros]}

## What are ${topic}?
${topic} have become essential tools for creators, businesses, and students. They save time and increase productivity.

## Top 5 Benefits
1. **Save Time** - Automate repetitive tasks
2. **Free Access** - No subscriptions needed
3. **Easy to Use** - No technical skills required
4. **Instant Results** - Get output in seconds
5. **Works Everywhere** - Browser-based

## How to Get Started
1. Choose the right tool for your needs
2. Follow the simple 3-step process
3. Export and use your results

## Conclusion
${topic} are transforming how we work. Start using them today to boost your productivity.

---
*Generated by Promptoolhub Blog Generator*`
  }

  const blog = generate()

  return (
    <main className="max-w-4xl mx-auto p-6">
      <h1 className="text-3xl font-bold mb-6">✍️ Blog Generator</h1>

      <div className="flex gap-3 mb-4">
        <input value={topic} onChange={e=>setTopic(e.target.value)} className="flex-1 border rounded-lg p-3" placeholder="Enter blog topic..." />
        <select value={tone} onChange={e=>setTone(e.target.value)} className="border rounded-lg px-4">
          <option value="informative">Informative</option>
          <option value="casual">Casual</option>
          <option value="professional">Professional</option>
        </select>
      </div>

      <div className="bg-white border rounded-lg p-6 max-h-[500px] overflow-auto">
        <pre className="whitespace-pre-wrap font-sans text-sm">{blog}</pre>
      </div>

      <div className="flex gap-2 mt-4">
        <button onClick={()=>navigator.clipboard.writeText(blog)} className="bg-indigo-600 text-white px-6 py-2 rounded-lg">Copy Blog</button>
        <button onClick={()=>{const blob=new Blob([blog],{type:'text/markdown'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=`${topic.replace(/\s+/g,'-')}.md`; a.click()}} className="border px-6 py-2 rounded-lg">Download.md</button>
      </div>
    </main>
  )
}
